# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=b'QUEUED', max_length=20)),
                ('DLstatus', models.CharField(default=b'QUEUED', max_length=20)),
                ('DCstatus', models.CharField(default=b'N/A', max_length=20)),
                ('SAstatus', models.CharField(default=b'N/A', max_length=20)),
                ('DAstatus', models.CharField(default=b'N/A', max_length=20)),
                ('package_name', models.CharField(db_index=True, max_length=100)),
                ('app_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=30)),
                ('md5', models.CharField(db_index=True, max_length=100)),
                ('sha1', models.CharField(db_index=True, max_length=100)),
                ('uploaded', models.DateField(auto_now_add=True)),
                ('targetSDK', models.CharField(blank=True, max_length=10)),
                ('minSDK', models.CharField(blank=True, max_length=10)),
                ('bayesResult', models.NullBooleanField()),
                ('bayesConfidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('sourcesUploaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='App_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.App')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='App_metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('version_string', models.CharField(blank=True, max_length=30)),
                ('author', models.CharField(blank=True, max_length=80)),
                ('date_upload', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.App')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicTestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('count', models.IntegerField()),
                ('description', models.TextField()),
                ('last_check', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Java_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=300)),
                ('app', models.ManyToManyField(to='frontpage.App')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('perm_description', models.TextField()),
                ('perm_danger', models.TextField()),
                ('app', models.ManyToManyField(to='frontpage.App')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.App')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.App')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.App')),
            ],
        ),
        migrations.CreateModel(
            name='Sourcefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file_contents', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.App')),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilityResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('confidence', models.CharField(max_length=10, null=True)),
                ('severity', models.CharField(max_length=20, null=True)),
                ('dynamicTest', models.BooleanField(default=False)),
                ('scheduledForDT', models.BooleanField(default=False)),
                ('dynamic_test_params', models.TextField(null=True)),
                ('vuln_class', models.CharField(max_length=300, null=True)),
                ('vuln_method', models.CharField(max_length=300, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.App')),
            ],
        ),
        migrations.AddField(
            model_name='dynamictestresults',
            name='vuln',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.VulnerabilityResult'),
        ),
        migrations.AddField(
            model_name='app_comments',
            name='vuln',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontpage.VulnerabilityResult'),
        ),
        migrations.AddField(
            model_name='activity',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.App'),
        ),
    ]
